export default async function fetchFlowers() {
  return [
    {
      id: 1,
      title: 'Dandelion',
      description: 'A soft, delicate flower known for its bright yellow petals that transform into fluffy seed heads.',
      image: 'https://th.bing.com/th/id/OIP.vMX8lBVn_Np_QnqriYLrNgHaFJ?w=265&h=185&c=7&r=0&o=5&dpr=1.3&pid=1.7',
      price: 159,
      summary: 'Dandelions are often overlooked but are full of nutritional value. Their bright yellow flowers are not only beautiful but also edible, adding a unique flavor to salads and teas. Additionally, dandelions are known for their medicinal properties, including promoting liver health and acting as a natural diuretic.',
    },
    {
      id: 2,
      title: 'Red Rose',
      description: 'The quintessential symbol of love and passion, the red rose has been cherished for centuries for its beauty and fragrant aroma.',
      image: 'https://th.bing.com/th/id/OIP.-zLJIo_r5AKTUx_b865QdQAAAA?rs=1&pid=ImgDetMain',
      price: 129,
      summary: 'The red rose is a timeless symbol of love and passion, cherished in various cultures for centuries. Its deep red petals and sweet fragrance evoke feelings of romance, making it a popular choice for gifts and celebrations. Beyond their beauty, red roses also have a rich history in art and literature, representing deep emotions and connections.',
    },
    {
      id: 3,
      title: 'Sunflower',
      description: 'Known for their bright and cheerful appearance, sunflowers are a symbol of happiness, positivity, and loyalty.',
      image: 'https://th.bing.com/th/id/OIP.c5S6MAz5Kr6jh0mXYTeKSQHaE8?w=284&h=189&c=7&r=0&o=5&dpr=1.3&pid=1.7',
      price: 199,
      summary: 'Sunflowers are not just strikingly beautiful; they also play a vital role in supporting biodiversity. Known for their unique ability to track the sun, these vibrant flowers are a source of nourishment for bees and other pollinators. Additionally, sunflowers produce seeds that are not only delicious but also packed with nutrients, making them a healthy snack option.',
    },
    {
      id: 4,
      title: 'Lavender',
      description: 'Known for its soothing aroma and calming properties, lavender is often used in aromatherapy and skincare, symbolizing purity and tranquility.',
      image: 'https://fthmb.tqn.com/xjHNZXhCKeE02l_KqGovZqZzifg=/5000x3300/filters:fill(auto,1)/lavender-in-bloom-big-56a5831a3df78cf77288ab2b.jpg',
      price: 250,
      summary: 'Lavender is revered for its calming and relaxing properties, making it a staple in aromatherapy. Its fragrant purple blooms not only add beauty to gardens but also attract beneficial pollinators. Additionally, lavender oil is commonly used in skincare products for its soothing effects and delightful scent.',
    },
    {
      id: 5,
      title: 'Lily',
      description: 'Elegant and fragrant, lilies are often associated with purity and refined beauty.',
      image: 'https://th.bing.com/th/id/OIP.lWJ6P7WcIdBNFJYOKBGAdgHaEy?rs=1&pid=ImgDetMain',
      price: 180,
      summary: 'Lilies are a symbol of purity and refined beauty, often used in bouquets for weddings and celebrations. Their elegant petals and sweet fragrance captivate admirers, making them a popular choice for floral arrangements. With a variety of species, lilies bloom in numerous colors, adding vibrancy to any garden.',
    },
    {
      id: 6,
      title: 'Tulip',
      description: 'Tulips are vibrant flowers that symbolize spring and renewal, available in a variety of colors.',
      image: 'https://images2.alphacoders.com/544/544058.jpg',
      price: 149,
      summary: 'Tulips are a classic symbol of spring, heralding the arrival of warmer weather with their vibrant blooms. Available in a stunning array of colors, these flowers can brighten any garden or floral arrangement. Tulips are also known for their unique shape, which adds elegance and charm to any setting.',
    },
    {
      id: 7,
      title: 'Orchid',
      description: 'Known for their exotic beauty, orchids are delicate flowers that symbolize love, luxury, and beauty.',
      image: 'https://th.bing.com/th/id/OIP.3lRJ3nAcCGKQohr4Ox71lQHaEo?rs=1&pid=ImgDetMain',
      price: 300,
      summary: 'Orchids are a symbol of luxury and beauty, renowned for their exotic and intricate blooms. With thousands of species, these flowers come in an array of colors and shapes, captivating plant enthusiasts worldwide. Orchids require specific care but reward growers with stunning, long-lasting flowers.',
    },
    {
      id: 8,
      title: 'Cherry Blossom',
      description: 'Famous for their breathtaking blooms, cherry blossoms represent the beauty and transience of life.',
      image: 'https://static.toiimg.com/photo/msid-71822251,width-96,height-65.cms',
      price: 220,
      summary: 'Cherry blossoms are celebrated for their ephemeral beauty, with stunning pink flowers that bloom for a short period each spring. These delicate blossoms symbolize the transient nature of life, making them a poignant reminder to cherish every moment. Festivals dedicated to cherry blossoms attract thousands, showcasing their cultural significance.',
    },
    {
      id: 9,
      title: 'Peony',
      description: 'Peonies are lush, fragrant flowers that symbolize romance and prosperity.',
      image: 'https://i.pinimg.com/originals/cc/68/c2/cc68c263d6c5333db76a814ef65631f1.jpg',
      price: 199,
      summary: 'Peonies are known for their lush blooms and delightful fragrance, often associated with romance and prosperity. These flowers come in a variety of colors, making them a favorite for weddings and special occasions. Their peony buds add texture and elegance to floral arrangements, creating a stunning visual appeal.',
    },
    {
      id: 10,
      title: 'Marigold',
      description: 'With their vibrant orange and yellow hues, marigolds are often associated with warmth and optimism.',
      image: 'https://facts.net/wp-content/uploads/2023/08/13-extraordinary-facts-about-marigold-1693316047.jpg',
      price: 180,
      summary: 'Marigolds are celebrated for their bright orange and yellow hues, radiating warmth and positivity. Often used in gardens for pest control, these flowers are not only beautiful but also practical. Marigolds are commonly associated with celebrations and are a popular choice for festive decorations.',
    },
  ];
}
